apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpackerr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: unpackerr
  template:
    metadata:
      labels:
        app: unpackerr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - beholder
      securityContext:
        fsGroup: 1000
      containers:
        - name: unpackerr
          image: golift/unpackerr:0.15.2
          securityContext:
            readOnlyRootFilesystem: false
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
              - /scripts/check.sh
              - /downloads
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          env:
            - name: TZ
              value: "Australia/Adelaide"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UN_RADARR_0_URL
              value: "http://radarr.media.svc.cluster.local:7878"
            - name: UN_RADARR_0_API_KEY
              valueFrom:
                secretKeyRef:
                  name: unpackerr-secret
                  key: RADARR_API_KEY
            - name: UN_SONARR_0_URL
              value: "http://sonarr.media.svc.cluster.local:8989"
            - name: UN_SONARR_0_API_KEY
              valueFrom:
                secretKeyRef:
                  name: unpackerr-secret
                  key: SONARR_API_KEY
            - name: UN_TRANSMISSION_0_URL
              value: "http://transmission.media.svc.cluster.local:9091"
          volumeMounts:
            - name: downloads
              mountPath: /downloads
            - name: nfs-healthcheck
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: unpackerr-downloads
        - name: nfs-healthcheck
          configMap:
            name: nfs-healthcheck
            defaultMode: 0755
