apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config-longhorn
  namespace: infra
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi