apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
