apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      hostNetwork: false
      containers:
        - name: wireguard
          image: linuxserver/wireguard:1.0.20260223
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: false
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Australia/Adelaide"
            - name: SERVERURL
              value: "theorangeserver.net"
            - name: SERVERPORT
              value: "51820"
            - name: PEERS
              value: "phone"
            - name: PEERDNS
              value: "1.1.1.1"
            - name: INTERNAL_SUBNET
              value: "10.10.50.0"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: wireguard
