apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: app
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-world
  namespace: app
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-world-nether
  namespace: app
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-world-end
  namespace: app
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
